#
# The Creative Commons Attribution 4.0 International License (CC-BY)
#
# Copyright (c) 2015 Snakepit Software
# Author: Rodney C Forbes   <5n4k3@snakepitsoftware.com>
#
# This work is licensed under the Creative Commons Attribution
# 4.0 International License. To view a copy of this license,
# visit http://creativecommons.org/licenses/by/4.0/.
#

# This file is sourced by bash for login shells.

# We still want to do everything in .bashrc.
[ -f ~/.bashrc ] && . ~/.bashrc

# set PATH so it includes user's private bin if it exists
if [ -d ${HOME}/bin ]; then
    PATH="${HOME}/bin/${OSTYPE}:${HOME}/bin:${PATH}"
fi

if [ ${OS:=""} == "darwin" ]; then
    PATH="${PATH}:/usr/local/git/bin"
fi

export PATH
