#
# The Creative Commons Attribution 4.0 International License (CC-BY)
#
# Copyright (c) 2015 Snakepit Software
# Author: Rodney C Forbes   <5n4k3@snakepitsoftware.com>
#
# This work is licensed under the Creative Commons Attribution
# 4.0 International License. To view a copy of this license,
# visit http://creativecommons.org/licenses/by/4.0/.
#

# This file is sourced by bash for login shells.

# We still want to do everything in .bashrc.
[ -f ~/.bashrc ] && . ~/.bashrc

# set PATH to include /sbin
PATH="/sbin:${PATH}"

# set PATH so it includes user's private bin if it exists
if [ -d ${HOME}/bin ]; then
  PATH="${HOME}/bin/${KERNEL_NAME}:${HOME}/bin:${PATH}"
fi


# Be sure to include local settings.
[ -f ~/.bash_profile_local ] && . ~/.bash_profile_local

export PATH

SSH_ENV="$HOME/.ssh/environment"

unset start_agent
function start_agent {
  echo "Initializing new SSH agent..."
  /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
  echo succeeded
  chmod 600 "${SSH_ENV}"
  . "${SSH_ENV}" > /dev/null
  /usr/bin/ssh-add 2>&1
}

# Source SSH settings, if applicable

if [ -f "${SSH_ENV}" ]; then
  . "${SSH_ENV}" > /dev/null
  #ps ${SSH_AGENT_PID} doesn't work under cygwin
  ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
    start_agent
  }
else
  start_agent
fi

