#
# The Creative Commons Attribution 4.0 International License (CC-BY)
#
# Copyright (c) 2015 Snakepit Software
# Author: Rodney C Forbes   <5n4k3@snakepitsoftware.com>
#
# This work is licensed under the Creative Commons Attribution
# 4.0 International License. To view a copy of this license,
# visit http://creativecommons.org/licenses/by/4.0/.
#

# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen!!

# New files should only be writable by the user
umask 022

# Disable history until our environment is fully configured
set +o history

# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
  # Shell is truly non-interactive.  Be done now!
  return
fi

###########################################
### From here down, we are interactive. ###
###########################################

###########################################
### Start with some reasonable defaults ###
###########################################
if [ -n ${BASH:-""} ]; then
  [ -r /etc/bashrc ] && . /etc/bashrc
fi

# Ultimately what would be most useful would be something like ...
#       $KERNEL_ARCH == "x64"
#       $KERNEL_NAME == "linux"
#       $KERNEL_VERS == "3.19.0"
#       $OS_NAME     == "Linux"
#       $OS_DISTRO   == "Ubuntu"
#       $OS_RELEASE  == "15.04"
#
# uname can provide some of this information, but it's not consistant across
# platforms.
#       On OS/X Yosemite (10.4) :
#           `uname -m` == "x86_64"
#           `uname -p` == "i386"
#           `uname -i` == ERROR
#           `uname -o` == ERROR
#       On Lubuntu 15.04 :
#           `uname -m` == "i686"
#           `uname -p` == "i686"
#           `uname -i` == "i686"
#           `uname -o` == "GNU/Linux"
#
# Other approaches to getting some of this information that really can't always
# be relied on because they might not be installed would be 'python -mplatform'
# and 'lsb_release' and 'gcc --version'
#
# Other kind of hackish methods include using the contents of files like
# /etc/issue and /etc/version
#
# /bin/bash provides ...
#       On OS/X Yosemite (10.4) :
#            $HOSTTYPE      == x86_64
#            $MACHTYPE      == x86_64-apple-darwin14
#            $OSTYPE        == darwin14
#       On Lubuntu 15.04 :
#            $HOSTTYPE      == x86_64
#            $MACHTYPE      == x86_64-pc-linux-gnu
#            $OSTYPE        == linux-gnu
#       On MinGW64 BASH :
#            $MSYSTEM_CARCH == x86_64
#            $MSYSTEM_CHOST == x86_64-w64-mingw32
#            $OS            == Windows_NT
#            $MINGW_CHOST   == x86_64-w64-mingw32
#            $MSYSTEM       == MINGW64
#
# os-release is a recent thing and works great if you have it

# These two seem to be reliable and straight forward
KERNEL_NAME=$(uname -s)
[ -z ${KERNEL_NAME} ] && [ "${OS}" = "Windows_NT" ] && KERNEL_NAME=${OS}
KERNEL_NAME=$(echo ${KERNEL_NAME} | tr "[:upper:]" "[:lower:]")
export KERNEL_NAME
KERNEL_ARCH=$(getconf LONG_BIT)
if [ ${KERNEL_ARCH} = 64 ]; then
  export KERNEL_ARCH="x64"
else
  export KERNEL_ARCH="x86"
fi

# These however are not, but I'm really not using any of these yet
if [ ${KERNEL_NAME} = "darwin" ]; then
  OS_NAME=MacOS
  export KERNEL_VERS=$(uname -r)
  export OS_DISTRO="OS/X"
  export OS_RELEASE=$(sw_vers -productVersion)
elif [ ${KERNEL_NAME} = "linux" ]; then
  OS_NAME=Linux
  export KERNEL_VERS=$(uname -r)
  if [ -f /etc/os-release ]; then
    . /etc/os-release
    export OS_DISTRO=$NAME
    export OS_RELEASE=$VERSION
  elif [ -f /etc/lsb-release ]; then
    . /etc/lsb-release
    export OS_DISTRO=$DISTRIB_ID
    export OS_RELEASE=$DISTRIB_DESCRIPTION
  elif [ -f /etc/debian_version ]; then
    export OS_DISTRO=Debian  # XXX or Ubuntu??
    export OS_RELEASE=$(cat /etc/debian_version)
  elif [ -f /etc/redhat-release ]; then
    OS_MAJOR_VERSION=`sed -rn 's/.*([0-9])\.[0-9].*/\1/p' /etc/redhat-release`
    OS_MINOR_VERSION=`sed -rn 's/.*[0-9].([0-9]).*/\1/p' /etc/redhat-release`
    export OS_DISTRO="RedHat"
    export OS_RELEASE="${OS_MAJOR_VERSION}.${OS_MINOR_VERSION}"
  else
    export OS_DISTRO=UNKNOWN
    export OS_RELEASE=UNKNOWN
  fi
elif [ "${KERNEL_NAME}" == "windows_nt" ]; then
  OS_NAME=Windows
  #OS_DISTRO=
  #OS_RELEASE=
elif [ "${KERNEL_NAME}" ~= ^mingw ]; then
  OS_NAME=Windows
  OS_DISTRO=${MSYSTEM}
  #OS_RELEASE=
fi

#####################
### Shell Options ###
#####################

# These should be ON
set -o braceexpand
set -o emacs
set -o hashall
set -o histexpand
set -o interactive-comments
set -o monitor

# These should also be ON
shopt -s checkwinsize
shopt -s cmdhist
shopt -s expand_aliases
shopt -s extquote
shopt -s force_fignore
shopt -s histappend
shopt -s hostcomplete
shopt -s interactive_comments
shopt -s login_shell
shopt -s progcomp
shopt -s promptvars
shopt -s sourcepath
shopt -s extglob

# These should be OFF
set +o allexport
set +o errexit
set +o errtrace
set +o functrace
set +o ignoreeof
set +o keyword
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o nounset
set +o onecmd
set +o physical
set +o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace

# These should also be OFF
shopt -u cdable_vars
shopt -u cdspell
shopt -u checkhash
shopt -u dotglob
shopt -u execfail
shopt -u extdebug
shopt -u extglob
shopt -u failglob
shopt -u gnu_errfmt
shopt -u histreedit
shopt -u histverify
shopt -u huponexit
shopt -u lithist
shopt -u mailwarn
shopt -u no_empty_cmd_completion
shopt -u nocaseglob
shopt -u nocasematch
shopt -u nullglob
shopt -u restricted_shell
shopt -u shift_verbose
shopt -u xpg_echo

######################
### Prompt Related ###
######################
# Shorten the working directory for our prompt
#   /dir1/dir2/dir3/dir4/dir5  = /dir1/.../dir4/dir5
#   ~/dir1/dir2/dir3/dir4/dir5 = ~/dir1/.../dir4/dir5
function getshortenedpath() {
  pwd | awk -v home=$HOME -v num_elem=5 '// {
          sub(home,"~",$0);
          n = split($0, x, "/");
          s = ((n <= num_elem)? $0: x[1] "/" x[2] "/.../" x[n-1] "/" x[n]);
          print s;
          exit (0);
          }'
}

function getgitinformation() {
  if [[ $(git rev-parse --git-dir 2> /dev/null) ]]; then
    GITPROMPT="[$(git rev-parse --abbrev-ref HEAD)]"
    # git status --untracked-files=all --ignore-submodules=all --porcelain --branch
  fi
  echo ${GITPROMPT:=""}
}

. ~/bin/git-prompt.sh
GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWSTASHSTATE=1
GIT_PS1_SHOWUNTRACKEDFILES=1
GIT_PS1_SHOWUPSTREAM="verbose name"
GIT_PS1_DESCRIBESTYLE=branch
PROMPT_DIRTRIM=3
if [ ${SHLVL} -eq 1 ]; then
  #export PS1="[\\u@\\h]\$(__git_ps1 "[%s]")[\w]\\$"
  export PS1="[\\u@\\h]\$(__git_ps1 "[%s]")[\$(getshortenedpath)]\\$"
else
  #export PS1="[\\u@\\h]\$(__git_ps1 "[%s]")[\w][${SHLVL}]\\$"
  export PS1="[\\u@\\h]\$(__git_ps1 "[%s]")[\$(getshortenedpath)][${SHLVL}]\\$"
fi

#############################
### Environment Variables ###
#############################
# cd search path
export CDPATH=".:~:~/Development"

# Ignore duplicates and ls (with no arguments) as well as built-ins like bg, fg and exit
export HISTIGNORE="&:[ ]*:ls:[bf]g:exit"
# How many history items to keep track of
export HISTSIZE=100
#export HISTSIZE=1000000
# How many history items to save when shell exits
export HISTFILESIZE=500
#export HISTFILESIZE=1000000000
export HISTTIMEFORMAT='%a %T '
export QUOTING_STYLE=literal
#export QUOTING_STYLE=escape

#export TERM='xterm'
# If the $term variable is xterm, change it to 256 colors!
if [ "$TERM" = "xterm" ]; then
    # No it isn't, it's gnome-terminal
    export TERM="xterm-256color"
fi
export VISUAL='vim'
export EDITOR="$VISUAL"
export GIT_EDITOR="$VISUAL"
export SUDO_EDITOR="$VISUAL"

#
# Aliases
#

[[ -f ~/.bash_alias ]] && . ~/.bash_alias

#
# Command Line Completion
#

[[ -f /etc/bash_completion ]] && . /etc/bash_completion
[[ -f ~/.bash_completion ]] && . ~/.bash_completion

#
# Key bindings are in .inputrc
#

#
# Wrap it all up
#

# Reenable the history
set -o history

