#!/bin/bash

set -e

# Settings used during creation of tunnel and primary ssh session
WS_USER=${WS_USER:=forbesr}
WS_IP=${WS_IP:=172.16.100.162}
LOCAL_PORT=${LOCAL_PORT:=9999}

# Keys to add to ssh-agent
KEYS="id_ecdsa id_rsa"

# Keeps track of settings used to start ssh-agent
SSH_ENV="$HOME/.ssh/environment"

function start_agent {
  echo "Initializing new SSH agent..."
  /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
  echo succeeded
  chmod 600 "${SSH_ENV}"
  . "${SSH_ENV}" > /dev/null
  /usr/bin/ssh-add
}

# Source SSH settings, if applicable
if [ -f "${SSH_ENV}" ]; then
  . "${SSH_ENV}" > /dev/null
  #ps ${SSH_AGENT_PID} doesn't work under cygwin
  ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
    start_agent
  }
else
  start_agent
fi

# Add SSH keys so that it doesn't prompt for the passphrases each time
for key in ${KEYS}; do
  ID="$(ssh-add -l | cut -d ' ' -f 3 | grep .ssh/${key})" || true
  if [ "${ID}" = "" ]; then
    ssh-add ~/.ssh/${key}
  fi
done

echo "Knocking ..."
fwknop -n ais_spa -R
sleep 2

echo "Starting SSH tunnel ..."
ssh -L ${LOCAL_PORT}:${WS_IP}:22 ais_spa -f sleep 10
sleep 2

echo "Connecting to workstation ..."
ssh -X ${WS_USER}@localhost -p ${LOCAL_PORT} -i ~/.ssh/ais.id_rsa

