#!/bin/bash

# shellcheck disable=SC1090
# shellcheck disable=SC2009

set -e

# Settings used during creation of tunnel and primary ssh session
: "${USER_NAME:=forbesr}"
: "${REMOTE_HOST:=172.16.100.162}"

: "${LOCAL_VNC_PORT:=9988}"
: "${REMOTE_VNC_PORT:=5900}"

: "${LOCAL_RDP_PORT:=9987}"
: "${REMOTE_RDP_PORT:=3389}"

# Keys to add to ssh-agent other than id_rsa and id_ecdsa
declare -a KEYS
KEYS+=("dell-7573.id_rsa" "mac-mini.id_rsa")

# Keeps track of settings used to start ssh-agent
SSH_ENV="${HOME}/.ssh/environment"

function start_agent {
  echo "Initializing new SSH agent..."
  /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
  echo succeeded
  chmod 600 "${SSH_ENV}"
  . "${SSH_ENV}" > /dev/null
  /usr/bin/ssh-add
}

# Source SSH settings, if applicable
if [ -f "${SSH_ENV}" ]; then
  . "${SSH_ENV}" > /dev/null
  #ps ${SSH_AGENT_PID} doesn't work under cygwin
  ps -ef | grep "${SSH_AGENT_PID}" | grep ssh-agent > /dev/null || {
    start_agent
  }
else
  start_agent
fi

# Add SSH keys so that it doesn't prompt for the passphrases each time
for key in "${KEYS[@]}"; do
  ID=$(ssh-add -l | cut -d ' ' -f 3 | grep .ssh/"${key}") || true
  if [ "${ID}" = "" ]; then
    ssh-add ~/.ssh/"${key}"
  fi
done

# SSH to remote host, setup requested local VNC/RDP tunnels
echo "Connecting to workstation ..."
declare -a SSH_FLAGS
# -L LOCAL_BIND_ADDRESS:LOCAL_BIND_PORT:REMOTE_ADDRESS:REMOTE_PORT
if [[ "${ENABLE_FEATURE}" == *"VNC"* ]]; then
  SSH_FLAGS+=("-L 127.0.0.1:${LOCAL_VNC_PORT}:127.0.0.1:${REMOTE_VNC_PORT}")
fi
if [[ "${ENABLE_FEATURE}" == *"RDP"* ]]; then
  SSH_FLAGS+=("-L 127.0.0.1:${LOCAL_RDP_PORT}:127.0.0.1:${REMOTE_RDP_PORT}")
fi

# shellcheck disable=SC2086
ssh -C -X "${SSH_FLAGS[@]}" ${SSH_EXTRA_FLAGS} "${USER_NAME}"@"${REMOTE_HOST}"

